### PR TITLE
Switch to stable release version of LMDB, fixes #140

### LINKED ISSUE #140: Included LMDB library is not a stable release version
The included LMDB library is not a release version of LMDB, it is the master branch with experimental code. In particular, it has experimental use of NTDLL, which we have determined to be source of significant performance, freezing, and instability issues on our servers. node-lmdb should use the stable release branch of lmdb for inclusion.

### PR DESCRIPTION
**Pull request by kriszyp**

### CODE REVIEW

**Comment by Venemo** [comment]
Thank you @kriszyp it sounds good, I just have two questions before merging this:

* Does this change result in any loss of functionality? For instance, will it still work on Windows? (I don't have a Windows computer at this time, so can't test for myself.)
* Did you use `git subtree` or a different method?

**Comment by kriszyp** [comment]
> * Does this change result in any loss of functionality? For instance, will it still work on Windows? (I don't have a Windows computer at this time, so can't test for myself.)
There is no loss in functionality. I have tested this and everything is still functioning properly (and all unit tests pass) on Windows. However, there is a _change_ in functionality: this stable release uses standard windows memory-mapping API which preallocates the entire size of the `mapSize` in the db files, whereas the `master` branch was using an experimental library that progressively allocates file space as memory is allocated. This experimental progressive allocation was the source of instabilities and bad performance we were seeing, and the standard preallocation technique should be more inline with other OSes.

> * Did you use `git subtree` or a different method?
I had just copied the files, as that's how I thought they had been put in there before; I guess I don't how to detect an existing subtree. I updated the PR to use a git subtree, although I couldn't figure out how to switch branches on the subtree, so I deleted and re-added the subtree. If there is another way to do this, I'd be glad to try again.

**Comment by Venemo** [comment]
> There is no loss in functionality. I have tested this and everything is still functioning properly (and all unit tests pass) on Windows.

Awesome, good to know!

> I had just copied the files, as that's how I thought they had been put in there before; I guess I don't how to detect an existing subtree.

Take a look here:  
https://github.com/Venemo/node-lmdb#managing-the-lmdb-dependency

You need the exact same lines, just replace `HEAD` with the branch (or tag) you want to use.

**Comment by kriszyp** [comment]
> Take a look here: https://github.com/Venemo/node-lmdb#managing-the-lmdb-dependency

I actually did attempt these steps (the first time basically the same without setting up remote). The problem is `git subtree` only seems to be capable of pull/merging, but we don't want to merge the lmdb release branch (mdb.RE/0.9) into the dev branch (mdb.master, that node-lmdb is currently using), because the dev branch has many commits that aren't and shouldn't be in the release branch. We really want the `git subtree` equivalent of switching branches (like `git checkout mdb.RE/0.9` on the subtree), but I can't figure out how to do that (without wiping out the whole directory and setting up the git subtree again).

**Comment by da77a** [comment]
Is there no practical way to reference an lmdb Lib (shared but support
static if needed?) rather then building the code within node-lmdb? The
motivation for this includes ensuring that all users of a shared lmdb
(different languages) are, if they all use the installed lib, using the
same version. Usually lmdb is pretty good at ensuring compatibility
although there have been some interesting changes in, for example, locking,
that at the very least make one cautious. And of course if using a
development version all compatibility bets are off...

**Comment by Venemo** [comment]
@kriszyp 

> I actually did attempt these steps (the first time basically the same without setting up remote). The problem is `git subtree` only seems to be capable of pull/merging [...]

All right, then. Just copying the files works too.

@da77a 

> Is there no practical way to reference an lmdb Lib (shared but support static if needed?) rather then building the code within node-lmdb?

I didn't find a good way to do this. If you want `npm install node-lmdb` to "just work" then you cannot expect the user to install lmdb on their own. There have been some other native node packages that did this, and their repo was full of issues about the users being confused by the missing system library, and this is why I chose to embed the lmdb code in the node module.

Another possibility would be to offer an alternative module named `node-lmdb-shared` that does use the system's shared lmdb library. The only difference between that and the upstream `node-lmdb` would be the `binding.gyp` and `package.json` so it would be pretty easy to maintain. You are welcome to make such a module if you want to.

**Pull request merged**
