### PR TITLE
zero-copy version of `getBinary` and internal version of `getString`

### PR DESCRIPTION
**Pull request by braydonf**
Adds new zero-copy version of `getBinary` and `getCurrentBinary` as `getBinaryUnsafe` and `getCurrentBinaryUnsafe`. It uses `Nan::NewBuffer` instead of `Nan::CopyBuffer`. 

Renames `getString` as `getStringUnsafe` that implements `ExternalStringResource` and adds new method `getString` that should be garbage collected by v8.

Adds benchmarks for above methods that can be run with:
```
npm run benchmark
```
closes: https://github.com/Venemo/node-lmdb/issues/49, closes: https://github.com/Venemo/node-lmdb/issues/69 and closes: https://github.com/Venemo/node-lmdb/issues/71

### CODE REVIEW

**Comment by braydonf** [comment]
Results from benchmarks are surprisingly showing this as the fastest:
```cpp
Local<Value> valToString(MDB_val &data) {
    auto str = Nan::New<v8::String>((uint16_t*)data.mv_data);
    return str.ToLocalChecked();
}
```

**Comment by Venemo** [comment]
@braydonf Interesting, do you mean that `getString` is even faster than `getStringUnsafe`?

**Comment by braydonf** [comment]
Yes, by a small amount.

**Comment by Venemo** [comment]
That is very weird!

**Pull request merged**
