### PR TITLE
Add Node.js 0.12 and io.js support

### PR DESCRIPTION
**Pull request by justmoon**
Convert to [NAN](https://github.com/rvagg/nan) to support recent versions of Node.js (0.12.x) and io.js (1.x).

### CODE REVIEW

**Comment by Venemo** [comment]
Awesome! Thank you :)

**Comment by kodeninja** [comment]
Is this actually fixed in `0.2.2`? I just tried installing it with `node 0.12.4` (on `OS X 10.10.3`) and it barfed:

```
$ npm i node-lmdb
\
> node-lmdb@0.2.2 install /private/tmp/test-node12/node_modules/node-lmdb
> node-gyp rebuild

2015-06-30 13:13:35.240 xcodebuild[96487:2624847] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XToDo.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-06-30 13:13:35.245 xcodebuild[96487:2624847] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PluginConsole.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-06-30 13:13:35.245 xcodebuild[96487:2624847] [MT] PluginLoading: Required plug-in compatibility UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
CC(target) Release/obj.target/node-lmdb/libraries/liblmdb/mdb.o
        ../libraries/liblmdb/mdb.c:8506:46: warning: data argument not used by format string [-Wformat-extra-args]
(int)mr[i].mr_pid, (size_t)mr[i].mr_tid, txnid);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
        /usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
__builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
^
1 warning generated.
        CC(target) Release/obj.target/node-lmdb/libraries/liblmdb/midl.o
CXX(target) Release/obj.target/node-lmdb/src/node-lmdb.o
In file included from ../src/node-lmdb.cpp:24:
../src/node-lmdb.h:58:24: error: expected class name
class EnvWrap : public ObjectWrap {
^
../src/node-lmdb.h:81:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> ctor(const Arguments& args);
^~~~~~~~~
            v8::internal::Arguments
    /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
    class Arguments;
^
    In file included from ../src/node-lmdb.cpp:24:
../src/node-lmdb.h:98:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> open(const Arguments& args);
^~~~~~~~~
            v8::internal::Arguments
    /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
    class Arguments;
^
    In file included from ../src/node-lmdb.cpp:24:
../src/node-lmdb.h:104:38: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> close(const Arguments& args);
^~~~~~~~~
            v8::internal::Arguments
    /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
    class Arguments;
^
    In file included from ../src/node-lmdb.cpp:24:
../src/node-lmdb.h:118:41: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> beginTxn(const Arguments& args);
^~~~~~~~~
            v8::internal::Arguments
    /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
    class Arguments;
^
    In file included from ../src/node-lmdb.cpp:24:
../src/node-lmdb.h:138:40: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> openDbi(const Arguments& args);
^~~~~~~~~
            v8::internal::Arguments
    /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
    class Arguments;
^
    In file included from ../src/node-lmdb.cpp:24:
../src/node-lmdb.h:148:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
            static Handle<Value> sync(const Arguments &args);
^~~~~~~~~
            v8::internal::Arguments
    /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
    class Arguments;
^
    In file included from ../src/node-lmdb.cpp:24:
../src/node-lmdb.h:156:24: error: expected class name
    class TxnWrap : public ObjectWrap {
    ^
    ../src/node-lmdb.h:174:37: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> ctor(const Arguments& args);
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        In file included from ../src/node-lmdb.cpp:24:
    ../src/node-lmdb.h:177:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> getCommon(const Arguments &args, Handle<Value> (*successFunc)(MDB_val&));
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        In file included from ../src/node-lmdb.cpp:24:
    ../src/node-lmdb.h:180:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> putCommon(const Arguments &args, void (*fillFunc)(const Arguments&, MDB_val&), void (*freeFunc)...
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        In file included from ../src/node-lmdb.cpp:24:
    ../src/node-lmdb.h:180:82: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> putCommon(const Arguments &args, void (*fillFunc)(const Arguments&, MDB_val&), void (*freeFunc)...
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        In file included from ../src/node-lmdb.cpp:24:
    ../src/node-lmdb.h:186:39: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> commit(const Arguments& args);
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        In file included from ../src/node-lmdb.cpp:24:
    ../src/node-lmdb.h:192:38: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> abort(const Arguments& args);
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        In file included from ../src/node-lmdb.cpp:24:
    ../src/node-lmdb.h:198:38: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> reset(const Arguments& args);
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        In file included from ../src/node-lmdb.cpp:24:
    ../src/node-lmdb.h:204:38: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> renew(const Arguments& args);
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        In file included from ../src/node-lmdb.cpp:24:
    ../src/node-lmdb.h:216:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> getString(const Arguments& args);
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        In file included from ../src/node-lmdb.cpp:24:
    ../src/node-lmdb.h:228:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> getBinary(const Arguments& args);
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        In file included from ../src/node-lmdb.cpp:24:
    ../src/node-lmdb.h:240:42: error: unknown type name 'Arguments'; did you mean 'v8::internal::Arguments'?
                static Handle<Value> getNumber(const Arguments& args);
    ^~~~~~~~~
                v8::internal::Arguments
        /Users/user/.node-gyp/0.12.4/deps/v8/include/v8.h:127:7: note: 'v8::internal::Arguments' declared here
        class Arguments;
    ^
        fatal error: too many errors emitted, stopping now [-ferror-limit=]
        20 errors generated.
                make: *** [Release/obj.target/node-lmdb/src/node-lmdb.o] Error 1
        gyp ERR! build error
        gyp ERR! stack Error: `make` failed with exit code: 2
        gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
        gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
        gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
        gyp ERR! System Darwin 14.3.0
        gyp ERR! command "node" "/Users/user/.nvm/versions/node/v0.12.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
        gyp ERR! cwd /private/tmp/test-node12/node_modules/node-lmdb
        gyp ERR! node -v v0.12.4
        gyp ERR! node-gyp -v v1.0.3
        gyp ERR! not ok
        npm ERR! Darwin 14.3.0
        npm ERR! argv "/Users/user/.nvm/versions/node/v0.12.4/bin/node" "/Users/user/.nvm/versions/node/v0.12.4/bin/npm" "i" "node-lmdb"
        npm ERR! node v0.12.4
        npm ERR! npm  v2.10.1
        npm ERR! code ELIFECYCLE

        npm ERR! node-lmdb@0.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
        npm ERR!
                npm ERR! Failed at the node-lmdb@0.2.2 install script 'node-gyp rebuild'.
                npm ERR! This is most likely a problem with the node-lmdb package,
                npm ERR! not with npm itself.
                npm ERR! Tell the author that this fails on your system:
                npm ERR!     node-gyp rebuild
        npm ERR! You can get their info via:
                npm ERR!     npm owner ls node-lmdb
        npm ERR! There is likely additional logging output above.

                npm ERR! Please include the following file with any support request:
                npm ERR!     /private/tmp/test-node12/npm-debug.log
```

**Comment by Venemo** [comment]
@kodeninja Thanks for the reminder. I just published a new version `0.3.0` which should contain the latest git master as of now.

**Comment by kodeninja** [comment]
@Venemo it works with `node 0.12.x` now :+1:!!! Thanks!

**Pull request merged**
