### PR TITLE
Fixes `v8::ObjectTemplate::Set()` non-primitive deprecation

### PR DESCRIPTION
**Pull request by braydonf**
Closes: https://github.com/Venemo/node-lmdb/issues/58

### CODE REVIEW

**Comment by Venemo** [comment]
@braydonf Thanks for this!

* Does it still compile on older node versions where this wasn't deprecated yet?
* Does it fix the error messages on the new node version?

**Comment by braydonf** [comment]
1. Yes, tested locally with these versions:
  - v0.10.46 - builds and tests pass *(after fixing issues with buffer offsets being undefined)*
  - v0.12.15 - builds *(with many warnings)* and tests pass
  - v4.4.5 - builds and tests pass
  - v5.7.1 - builds and tests pass
  - v6.2.0 - builds *(still a few deprecation warnings)* and tests pass
2. It clears the stack traces with deprecation warnings when running the tests

**Comment by Venemo** [comment]
@braydonf Could you please rebase this patch on the current master?

**Comment by braydonf** [comment]
Rebased

**Comment by Venemo** [comment]
Awesome, thank you!

**Pull request merged**
