### PR TITLE
Consideration of adding support for asynchronous put, batch, refs #46

### PR DESCRIPTION
**Pull request by kriszyp**
I wanted to put this out for consideration, as a potential starting point (a work-in-progress) for asynchronous support for some write operations, at least partially addressing #46. This works by submitting an operation, or a set of operations to an async worker, and then letting the worker perform the entire transaction.

However, as mentioned in #46 , there may be some important reasons why this might actually not belong in node-lmdb. In particular, if I understand correctly, the intent of node-lmdb is to provide a relatively direct binding to the LMDB api. On the other hand, these asynchronous methods are really building higher-level constructs to perform multiple LMDB calls together. And there are a number of reasons why this is probably the right way to do async interaction with LMDB. First, trying to do separate asynchronous puts/removes *and* commits actions, creates very complex sequencing operations for users, and running these puts/remove and commits in separate threads isn't even necessarily safe or supported within a single LMDB transaction (if two async workers concurrently put and committed on the same transaction, the results would be completely non-deterministic, and potentially crash). Whereas performing entire transactions in a separate thread is safer and simpler to reason about.

I believe creating a useful, efficient, and consistent asynchronous interface to LMDB probably means abstracting away transaction management, and letting this be handled by the package, so that it can properly handle the entire transaction in a single worker thread to maintain thread safety. There are a number of additional conveniences that would make this more useful, like concurrent queuing of multiple operations, and immediate get consistency by looking at queue puts/removes, that are really higher-level concerns than a package concerned more with providing direct bindings to LMDB.

Anyway, if you do want this functionality integrated into node-lmdb, I'd be happy to continue with this branch/PR. But if you feel this functionality goes beyond the spirit of node-lmdb, I'd be happy to create a separate project that builds on the low-level functionality of node-lmdb (although if entails C++, I'm not sure if there is a way to use node-lmdb as an actual package dependency or not, but maybe as a sourcetree'ed dep) and provides higher-level asynchronous key-value interaction with more managed transactions. And I wouldn't think that would be strike against the usefulness of node-lmdb, but rather a demonstration of its low-level usefulness, that higher-level packages can build on it. However, I wanted to put this out for consideration for any feedback on the best way to proceed.

### CODE REVIEW

**Comment by Venemo** [comment]
@kriszyp First, thank you for putting so much effort into node-lmdb, it is very much appreciated.

Yes, this is something that I would gladly add to node-lmdb, if we manage to find a good way to do it. There are IMO two main obstacles:

1. A given transaction object must always be accessed by the same thread. Which means that if you do multiple put, get, etc. operations on a transaction, you must somehow ensure that all of those operations are done on the same thread. Your current patch just uses `Nan::AsyncQueueWorker` which only ensures it doesn't run on the main thread, but does **not** give you a way to run a given set of operations on the same thread.
2. For individual put, get, etc. operations, the overhead will bigger than what the actual operation takes. In the current version, the overhead is just a JavaScript->C++ context switch (which is already expensive). In the async version, the overhead will also include scheduling the operation on a different thread, then calling the callback, etc.

At the very least (1) is absolutely needed for correctness. Otherwise the node app may or may not randomly crash with a cryptic error message. One possible solution is [outlined in this StackOverflow post](https://stackoverflow.com/questions/16407158/in-a-native-node-module-how-can-i-make-sure-that-my-async-code-is-always-runnin) but I never got around to implementing it.

I guess there is no way around (2) and it's hard to say what the performance cost will be without measuring it. However we don't have to worry about it too much right now, there may be ways to deal with it later.

What do you think?

**Comment by kriszyp** [comment]
First, let me say that I actually think that `get` is a completely different subject, and should _not_ be asynchronous (at least single gets). I don't believe that async writes should imply we should also have async reads. There are a few reasons why write operations are much more appropriate for async than get/reads:
* Async is best suited for I/O operations, and get calls do not have _any_ explicit I/O. They are pure memory operations. Of course I/O can be triggered as a result of a page fault, but so can any memory access in any node program. On the otherhand, write operations do have explicit I/O (unless you have writeMap, noSync, and noMetaSync, in which case your database is prone to corruption on crashes, and we have observed that happens pretty easily).
* Consequently get operations are much faster. Like you said, they are often less than the cost of worker queuing. Write operations can be slower than worker queuing, and if you have multiple operations batched and have't disabled sync-on-commit, write transactions are much slower than worker queuing, the worker queuing becomes a negligible part of the cost of such a transaction.
* In terms of caller needs, get operations are heavily dependent on the _result_, whereas write operations are not. When a caller triggers a write, they typically aren't that concerned with the return value, other than verifying that it completed without error and the data has been flushed (assuming sync-on-commit hasn't been disabled). This means that it is really easy to batch a bunch of write operations together, fire them off, and wait for a single callback to verify completion. Whereas with get operations you almost always need to know the resulting data from each operation before you can continue with logical program execution.

So onto your questions :).

> 1. A given transaction object must always be accessed by the same thread.

So my intent (and I think the code properly does this) was that the worker thread would use its own private transaction, and _never_ share that transaction with another thread. This guarantees that variant (that the transaction will only be accessed one thread). Of course the implication of this is that there are async workers that are creating/using transactions that are not visible or accessible (and must never be accessible) to the main JS thread code or any other worker thread. The transactions that are being performed by the worker thread will only ever be operating on the write operation(s) that were submitted to it (no mixing with get operations on the main thread). I believe it is still feasible for the the main thread to create their own write transactions, but they would be complete separate. And I believe that write transaction locking will ensure that these transactions are serialized/sequenced (a thread that attempts to start a write transaction will be blocked if another thread has an open one, until it is done), but I haven't verified that (it could be done with mutexes if lmdb's file locking doesn't work).

> 2. For individual put, get, etc. operations

I kind of addressed this, but yes, individual operations (with sync disabled) generally wouldn't benefit. However, after using LMDB for a while, and dealing with a corrupted db after a crash, I believe that LMDB really _should_ be used with sync-on-commit, and to really achieve optimal efficiency, the best performing way for JS to interact with LMDB is to queue and batch as many write operations as possible, using higher-level logic to aggregate operations from an event turn, or with a short timeout, and then submit those operations together in a batch with proper sync-on-commit behavior. This both improves efficiency by decreasing transaction overhead of putting numerous writes in numerous transactions, but also allows the robustness of crash-proof syncing to work properly. And with multiple operations, culminating in a (potentially slow) sync, this is where execution in a worker thread really shines, allowing a lot of work to be done off-thread, with very low-cost single-call notification on completion.

The logic of queuing write operations, and potentially having get calls check queued writes for immediate-consistency, seems like it goes beyond the goals of node-lmdb, and might be closer to application logic, whereas maybe the async batch/put functionality is low-level enough for node-lmdb. But I don't know, I'm glad to contribute or separate out any functionality you want.

And as far asynchronous gets, as I said, I don't think single gets would benefit. But there *might* be a case for submitting a request for asynchronous retrieval of a range of keys for cursor traversal and retrieval in a separate thread, where a potentially large cursor traversal could be efficiently offloaded to another thread.

**Comment by Venemo** [comment]
Okay, so if I understand correctly you want to write a lot of data very fast, but you don't actually care about asynchronous reads. Is that correct?

If you don't care about generalizing the current API, then the task is much simpler than the whole big topic that we have discussed so far. In that case, I would propose to just add a method to `Env` like so. Not sure if an array of objects, or an array of arrays is a better solution (or a flat array maybe?). It could be like this:

```
var data = [
    [db1, "key1", "value1"],
    [db1, "key2", "value2"],
    [db1, "key3", "value3"],
]
env.batchPut(data, options, function() {
    console.log("done");
})
```

Then `batchPut` would create a write transaction, call `mdb_put` (taking into account the type of the input variables), and would take a similar `options` as the current functions, for consistency.

I think this is almost what you implemented in your `BatchWorker`. If you clean up that code a little bit, and move it to `Env`, then I would be happy to merge it.

Looking at your `PutWorker`, it breaks consistency with the current API ― it gives the impression that it's an async version of `put` but in reality it creates a separate transaction and everything under the hood, making it less intuitive for some users. However I think `batchPut` would do everything that `putAsync` does, so it's not really necessary to have the latter.

**Comment by kriszyp** [comment]
Yes, that is correct, I don't think there is the same value from asynchronous gets, that there is from writes, and like you said, I think just offering batched writes simplifies this. Or at least, we don't want to mix the concepts. Maybe someday, offering some type of asynchronous request for a range of values through cursor traversal would be nice, but it should be a completely separate transaction, absolutely no sharing a write transaction across threads.

> In that case, I would propose to just add a method to `Env` like so.
That's fine with me.

> Not sure if an array of objects, or an array of arrays is a better solution (or a flat array maybe)?
I had done an array of objects with "key" and "value" properties, but an array of arrays is fine with me.

It is worth noting that a batch should support both `put` *and* `del`. It is perfectly reasonable to include both of these in a batched transaction, and no reason to exclude deletes. In my code, I represented delete operations with an undefined "value" property, which allows for a nice compact array. If we did an array of arrays, I assume we could represent delete operations with two element arrays (the dbi and key, no value). Consequently, I don't think `batchPut` is the right name, since it is really just a batch of both types of operations.

Adding the `options` would presumably be for transaction options, I assume, and any other future options (could also specify if MDB_NOTFOUND on del should be treated as an error).

> I think `batchPut` would do everything that `putAsync` does, so it's not really necessary to have the latter.

I agree. I had started with `putAsync` to get going, but really it is just confusing, unnecessary, and extra complexity. The `batch` operation does everything we need.

**Comment by Venemo** [comment]
> Yes, that is correct, I don't think there is the same value from asynchronous gets, that there is from writes, and like you said, I think just offering batched writes simplifies this. Or at least, we don't want to mix the concepts.

Understood.

> I had done an array of objects with "key" and "value" properties, but an array of arrays is fine with me.

Well, if the main consideration is performance, then I'd assume that a flat array may perform best, since it needs fewer JS object creations. Shouldn't be too difficult to benchmark.

> It is worth noting that a batch should support both `put` _and_ `del`. It is perfectly reasonable to include both of these in a batched transaction, and no reason to exclude deletes.

Agreed.

> In my code, I represented delete operations with an undefined "value" property, which allows for a nice compact object. If we did an array of arrays, I assume we could represent delete operations with two element arrays (the dbi and key, no value).

I'd suggest to just use `null` for the deletions. If I recall correctly, the `get` operations return `null` when the key is not found, so this would be consistent with that.

> Consequently, I don't think `batchPut` is the right name, since it is really just a batch of both types of operations.

Agreed. What do you think would be the best name? `batchWrite`? I'm open to suggestions.

> Adding the `options` would presumably be for transaction options, I assume, and any other future options (could also specify if MDB_NOTFOUND on del should be treated as an error).

That too, and also the same key type logic that node-lmdb has with every other function.

**Comment by Venemo** [comment]
@kriszyp Nice work. I still thinkt hat flat arrays would be more performant, but if you measured it you can convince me about array of arrays.

**Comment by kriszyp** [comment]
Ah, I didn't realize you wanted to try out flat arrays. I can give that a try. There is more testing that I want to do on this anyway, before it is ready to merge.

**Comment by Venemo** [comment]
If there is a perf benefit to using flat arrays then I'd vote on using them. If not, then I think array of arrays is easier to read, so that's what I'd vote for.

**Comment by kriszyp** [comment]
After testing and using the batched write functionality for a while, I think there is one more piece of this that is pretty valuable. Batching writes and committing them asynchronously in separate transactions means that your writes can't really be atomically tied to any state that has been read, in a deterministic way, if the database could be written between the read and write (by other async actions or other processes). However, you can regain deterministic atomicity in a relatively simple and composable way by simply adding support for conditional writes, where the puts and deletes can have a db, key, value, and conditional value. So this PR branch has been updated with my proposed addition of conditional writes.

There are a few other additions in here as well. It now includes support for progressive updates (if you include a `progress` callback in the options), and it will return an array (to either callback) listing the sucess or non-success of the commits. I also added support for object or array defined write operations. The objects are little easier to use if there are a number of properties specified in a conditional write, but the arrays are presumably faster.

I did also test with completely flat array structure. I think there was a very slight increase in performance, but it seemed pretty small for how confusing it made the data structure.

**Comment by Venemo** [comment]
Thanks @kriszyp for your thorough work. If flat arrays are not noticably faster then I agree that they shouldn't be used for this. Do you think this is ready to get merged? If yes, I'll review it as soon as I can.

**Comment by kriszyp** [comment]
I think it is ready for merging, or at least for review. My C coding skills are rusty, so certainly welcome any suggestions/changes you want.

**Comment by Venemo** [comment]
@kriszyp As far as I understand this is superseeded by #150 right? If yes, please close it.

**Pull request closed without merging**
