### PR TITLE
compile for node 4.x

### LINKED ISSUE #38: node-lmdb doesn't compile against node 4.0.0

### PR DESCRIPTION
**Pull request by dasantonym**
this fork should fix #38 

works for me on mac os x 10.11 / node 4.2.1

### CODE REVIEW

**Comment by Venemo** [comment]
@dasantonym Thanks for your excellent work! :)

**Comment by mhart** [comment]
Excellent! If you could let us know when this has been released on npm, either here or on #38 – that would be great.

**Comment by dasantonym** [comment]
cool, thanks for merging this! although i must explicitly add that the work part here was done by @erichocean and i just spotted his fork.

**Comment by erichocean** [comment]
Nice! If you haven't already, please update the repository key in package.json to point to your repository. :)

**Comment by polidore** [comment]
+1 i would like to use this without cloning from git!

**Comment by Venemo** [comment]
Sorry for staying quiet for so long. I'll try to make this happen at the weekend. :)

**Comment by mhart** [comment]
A release of this would be great :+1:

**Pull request merged**
