### PR TITLE
Add compiler variable to binding.gyp

### PR DESCRIPTION
**Pull request by dschnei**
As I had problems using a different compiler for cross compiling (for ARM) I added a compiler variable to the binding. This shouldn't affect the default behavior.
But in case you are able to pass a different compiler.

In my case my gcc version was 7.x and my compiler version for cross compiling was 6.x. That's why I run into problems with the "conditions" for gcc_version >= 7

Best Regards,
Daniel

### CODE REVIEW

**Comment by Venemo** [comment]
Hi Daniel,

So do you want an environment variable or a node-gyp variable? One of your commits adds one, the other commit changes it to the other.

**Comment by dschnei** [comment]
Yes, that's true but I decided to use a node-gyp variable.
I think this is the cleaner solution and works fine for me.

**Comment by Venemo** [comment]
Since it seems to just affect the linux build, can you please add your variable under `"OS=='linux'"` please, maybe just above `gcc_version`? So that other people who read the gyp file don't get confused about it.

After that please squash them together to one commit, and I can merge it.

**Comment by dschnei** [comment]
Adding the variable just above `gcc_version` was my first try. But if I put it in this section I get an error from gyp: `gyp: Undefined variable compiler in binding.gyp while trying to load binding.gyp`
I have just tried it again but without success ...

I'm not very confident with the initialization of variables or their scoped in gyp files, sorry.

**Comment by Venemo** [comment]
@dschnei OK, then I just ask that you give a more descriptive name to the variable, to make it clear that it is only used when compiling on Linux.

**Comment by Venemo** [comment]
@dschnei Can you please squash together these commits?

**Comment by Venemo** [comment]
Squashed myself and merged.

**Pull request merged**
