### PR TITLE
Upgrade to the LMDB 1.0 master branch

### PR DESCRIPTION
**Pull request by kriszyp**
This now seems to be stable and working well with node-lmdb (using the provided defines).

### CODE REVIEW

**Comment by Venemo** [comment]
@kriszyp I'm not sure why GitHub doesn't let me merge this, but feel free to push it to the master branch. I believe you have commit access to it.

**Comment by kriszyp** [comment]
Thank you, I didn't even realize (or remember) that I had commit access. I went ahead merged this and added an example for detachBuffer. @Venemo can you npm publish this to a new version? I didn't upgrade the version because I wasn't sure if you wanted 0.8.1 or 0.9.0 (since it is major version upgrade of LMDB itself). (I assume I don't have npm publishing access).

**Comment by Venemo** [comment]
@kriszyp Yeah, I think I invited you as a contributor some while ago. Honestly, I haven't got much time for node-lmdb these days, so I was happy to see that you care about it.

Is it possible to give you npm publish access? If it is, I'd be happy to.

**Comment by kriszyp** [comment]
Thank you for the access, glad to help. And I am happy to directly commit to the repo (and let me know if you want more or less review of things). For NPM access, I believe you could add me as a maintainer at https://www.npmjs.com/package/node-lmdb/access (you have to login to npmjs.com). Thanks again!

**Comment by Venemo** [comment]
Awesome. I now added you as a maintainer on npm as well. Feel free to publish at your discretion.

I will probably look at the code from time to time, but I don't think I will have the time to do a day-to-day review of every commit. I haven't worked as a web or JS developer for some years now, and I also don't follow V8 development closely, so I'm afraid I'm only slowing down your progress right now.

My only request is to please try to keep up the good work of maintaining not just the code but also the documentation, example code and unit tests. Also, if you want to discuss stuff, you can reach out to me on my private email too.

Happy hacking!

**Pull request merged**
