### PR TITLE
Auto value type

### PR DESCRIPTION
**Pull request by druide**
I have extended the library with `put` and `get` methods accepting free value types. It is more comfortable to use. Also, prototype methods assignments need update due to deprecation warning. Internally in LMDB, value type is set by the first byte of data. Modification have 2 drawbacks:

- incompatability with previous data file format (1st byte is type now)
- binary type write performance degrade because of buffer copying

Regards!

### CODE REVIEW

**Comment by Venemo** [comment]
Hi,

Thanks for the code! Since you are proposing a major API break, I'll have to consider carefully what to do. Maybe it is more comfortable to you, but it will definitely break everyone else's code.

What kind of problems are you trying to solve with this?

**Comment by druide** [comment]
Hi Venemo!
I'm using multiple dbs with different value types (including JSON) in environment, with multiple writer classes, common parent class to update data and common reading method, using cursor. Samples:

```
UpdaterClass.prototype.update = function (dbi, rows, keyFn, dataFn, message)

...
var txn = env.beginTxn({readOnly: true});
var cursor = new env.Cursor(txn, dbi); // env is extended in JS
function getData (key, data) {
...
}
for (var found = cursor.goToFirst(); found; found = cursor.goToNext()) {
    cursor.get(getData );
}
cursor.close();
txn.abort();
```

To use this type of abstraction, I need to set value type for each DB (dbi), and db must contain values of one type only.

Proposed modification stores JS value type together with data (`put(dbi, key, anything)`), API is fully backward-compatible, but db file binary format is not.
I see possible improvement here - add some API flag to use native and extended binary db format.

**Comment by braydonf** [comment]
I disagree, using the first byte to store the data type should not be a concern at this part of the API. A `put` and `get` that handle buffers for both keys and values can handle any type of encoding scheme, including using the first byte to indicate the type, and can be implemented on top of that.

**Comment by Venemo** [comment]
@druide The idea is nice, but I generally agree with @braydonf here in that this sort of stuff would be out of scope for `node-lmdb` ― as it neither maps to the lmdb API, nor is what we intend to achieve in this binding.

In my (personal) opinion, this should be something in a separate module that builds on top of node-lmdb.

**Pull request closed without merging**
