### PR TITLE
Proper binary key support for cursors (and a fix to string handling)

### LINKED ISSUE #84: cursor 'goto' functions return garbage for buffer based keys.
On testing the new key as buffer functionally I've noticed that in the case of a buffer key the cursor 'goto' functions return a garbage string when I was expecting a buffer. 

Some test results showing this behaviour:

```
test putString
putString: k='a' (string), v='hello' (string)
putString: k='b' (object), v='goodbye' (string)
putString: k='c' (string), v='sayonara' (string)

test getString
getString: k='a' (string), v='hello' (string)
getString: k='b' (object), v='goodbye' (string)
getString: k='c' (string), v='sayonara' (string)

test cursor
goToFirst returned 'a' (string), getCurrentString returned 'hello' (string)
goToNext returned '杢漀漀搀戀礀攀' (string), getCurrentString returned 'goodbye' (string)
goToNext returned 'c' (string), getCurrentString returned 'sayonara' (string)
```

and the test code that produced them:

```
var lmdb = require('..');
var env = new lmdb.Env();
var fs = require('fs');

if (!fs.existsSync('test')) {
    fs.mkdirSync('test');
}
env.open({path: 'test', mapSize: 1024*1024});
var dbi = env.openDbi({name: "test", create: true});

function debugVar(v) {
    return "'" + v + "' (" + typeof v + ")";
}

const kvs = [
    {k: "a", v: "hello"},
    {k:  new Buffer("b"), v: "goodbye"},
    {k: 'c', v: "sayonara"},
];

console.log("test putString");
var t1 = env.beginTxn();
kvs.forEach(o => {
    console.log("putString: k="+debugVar(o.k)+", v="+debugVar(o.v));
    t1.putString(dbi,o.k,o.v);
})
t1.commit();

console.log("\ntest getString");
var t2 = env.beginTxn();
kvs.forEach(o => {
    console.log("getString: k="+debugVar(o.k)+", v="+debugVar(t2.getString(dbi,o.k)));
})
t2.commit();

console.log("\ntest cursor");
var t3 = env.beginTxn();
var cursor = new lmdb.Cursor(t3,dbi);

console.log("goToFirst returned "+debugVar( cursor.goToFirst() )+", getCurrentString returned "+debugVar( cursor.getCurrentString() ));
console.log("goToNext returned "+debugVar( cursor.goToNext() )+", getCurrentString returned "+debugVar( cursor.getCurrentString() ));
console.log("goToNext returned "+debugVar( cursor.goToNext() )+", getCurrentString returned "+debugVar( cursor.getCurrentString() ));

cursor.close();
t3.commit();
dbi.close();
env.close();
```

### PR DESCRIPTION
**Pull request by da77a**
Fixes #84 by introducing an explicit option (third parameter) to cursor constructor which, if set, always returns keys as buffers.

Also made a small adjustment to commit/ f5b80e696eca3a4116a21bc76042d47a20e60ce6 to avoid buffer overrun if mv_size is less than 2...

Included some tests.

Note I have limited this change to cursor - it is the only class that returns keys and needs this change. The change does not break any existing (correct) usage/code. I agree that it is common usage to use only one key "type" per dbi, but if you have a database with keys that have the "wrong" format and want to cursor over your db cleaning it up guess how many key types you need on the one dbi.... qed. imho. If someone wants to add a change to set the "default" key return type based on a new dbi parameter, be my guest. I don't need it so won't be making that change, and I think the semantics of a dbi with a specified "key type" are confusing unless you actually change the API to refuse to accept keys as Buffers if using a "string keys" dbi and similarly accept only Buffers if using a "binary keys" dbi. Doing so would break some existing code, whichever choice you make (unless you have a third dbi "compatibility" mode). All of which is more complexity than seems needed.

### CODE REVIEW

**Comment by Venemo** [comment]
@da77a Thanks for your work! I'll review it and merge as soon as I can.

**Comment by da77a** [comment]
@Venemo - would it help if I added some doc changes re this change and an example or 2?

**Comment by Venemo** [comment]
@da77a Yes, thank you. Sorry I haven't had the time yet to look through your patches, but I promise to get around to doing it this week.

**Comment by da77a** [comment]
@Venemo - Added the promised example and doc changes (sorry -about the delay - been busy). I took the liberty of a bit of a doc refactor as there are a lot of places that talk about similar concepts and I had difficulty adding yet more docs without it becoming repetitious. Any chance you could review the patches soon?

**Comment by da77a** [comment]
Latest addition is just to clear up that last tiny leak in #94 - in theory.

**Comment by Venemo** [comment]
@da77a Thanks man! Your changes are now merged.

**Comment by Venemo** [comment]
@da77a I merged with `git cherry-pick` (instead of the GitHub way), so you might have to rebase your branch... Sorry!

**Comment by Venemo** [comment]
@da77a One question though: why was it necessary to add `node` and `nodejs` to the `devDependencies`?

**Comment by Venemo** [comment]
@da77a One more question: what exactly is the difference between `stringKey` and `legacyStringKey`? Is there an actual need for the distinction?

**Comment by da77a** [comment]
Sorry about messing up your dev dependencies - this code has taken a few private forks along the way... Should have kept some of the "noise" out of my public repo. Wasn't really expecting such a long chain of changes to make it in unmolested anyway.

_legacyStringKey_ was only included so behaviour was unchanged if no new param passed to cursor c'tor. As I said in the docs, it was a deprecated mode/feature and likely to be removed as soon as an api breaking release was made. This appears to be now... See #84 discussion.

**Pull request closed without merging**
