### PR TITLE
Update package.json and dependencies

### PR DESCRIPTION
**Pull request by braydonf**

### CODE REVIEW

**Comment by braydonf** [comment]
Rebased to fix merge conflicts

**Comment by Venemo** [comment]
As an aside: the `^` prefix in front of a package version (as far as I know) means "the latest version that is compatible with the specified version". So it is not quite necessary, but I agree that it doesn't hurt to update those from time to time.

**Comment by Venemo** [comment]
Since I need to modify the package.json myself because of #61 I believe the simplest would be for me to reject this pull request and just make your suggested edits myself.

By the way @braydonf would you mind me adding your name to the contributors list? :)

**Comment by braydonf** [comment]
True, I was imagining that `^` was only applying to patch versions, updating isn't necessary. 

And wouldn't mind being added to the contributors list, thanks!

**Comment by Venemo** [comment]
Okay, it's done. :)

**Pull request closed without merging**
